# Generated by Django 3.2.12 on 2022-04-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schnr', models.IntegerField(auto_created=True)),
                ('nname', models.CharField(max_length=200)),
                ('vname', models.CharField(max_length=200)),
                ('klasse', models.CharField(max_length=20)),
                ('stufe', models.IntegerField()),
                ('geschlecht', models.CharField(max_length=20)),
                ('lauf', models.FloatField()),
                ('notelauf', models.IntegerField()),
                ('punktelauf', models.IntegerField()),
                ('sprung1', models.FloatField()),
                ('sprung2', models.FloatField()),
                ('sprung3', models.FloatField()),
                ('bestsprung', models.FloatField()),
                ('notesprung', models.IntegerField()),
                ('punktesprung', models.IntegerField()),
                ('wurfstoss1', models.FloatField()),
                ('wurfstoss2', models.FloatField()),
                ('wurfstoss3', models.FloatField()),
                ('bestwurfstoss', models.FloatField()),
                ('notewurfstoss', models.IntegerField()),
                ('punktewurfstoss', models.IntegerField()),
                ('punktemehrkampf', models.IntegerField()),
                ('bemerkung', models.TextField()),
            ],
        ),
    ]
