# Generated by Django 3.2.12 on 2022-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportcompetition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schueler',
            name='bemerkung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='bestsprung',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='bestwurfstoss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='lauf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='notelauf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='notesprung',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='notewurfstoss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='punktelauf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='punktemehrkampf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='punktesprung',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='punktewurfstoss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='sprung1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='sprung2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='sprung3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='wurfstoss1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='wurfstoss2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schueler',
            name='wurfstoss3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
