# Generated by Django 3.2.12 on 2022-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportcompetition', '0002_auto_20220408_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schueler',
            name='schnr',
            field=models.IntegerField(),
        ),
    ]
