# Generated by Django 3.2.12 on 2022-04-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportcompetition', '0005_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
